# Generated by Django 4.2.7 on 2023-11-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='userposts_p_created_567524_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='userposts_p_user_id_18e3d3_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='down_total',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up_total',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
