# Generated by Django 4.2.7 on 2023-11-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0004_post_content_post_created_post_down_total_post_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='userposts_p_created_567524_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='userposts_p_user_id_18e3d3_idx',
        ),
    ]
