# Generated by Django 4.2.7 on 2023-11-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0007_post_userposts_p_created_567524_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentvotes',
            options={'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
    ]
